### PR TITLE
Sync to Upstream and much more

### PR DESCRIPTION
**Pull request by catduckgnaf**
Hello!

I love the work you guys have done, I did find it a bit confusing with the name still being linkplay. I also can imagine issues if someone has this + linkplay for other devices.

1. I went ahead and renamed everything, for yamaha_soundbar
2.  changed the default MDI icon to mdi-soundbar
3. removed all of the excess sources, so we only have the three per the api, mini media player looks way better now!
4. Added documentation to readme on renaming sources
5. Sync with upstream changes  https://github.com/nagyrobi/home-assistant-custom-components-linkplay/commit/43a8d91cb13803f0fe90c9ed73b1a1707985d399

P.S. I realize I updated everything to my repository. I am not trying to steal the project from you, that was just my testing. I would of course like to contribute to the main project, and if you like these changes I will revert those, or I am happy to keep it going in a separate repo, especially given the name change.

P.S.S. I also do plan to see if power on/off can be stable, especially over ethernet, for our devices, so hopefully that will be a PR you will consider as well.

### CODE REVIEW

**Comment by osk2** [comment]
Thank you for submitting the PR, @catduckgnaf. The changes look good to me.

However, considering that name changing is a breaking change, we should implement a migration to update the configuration automatically. (using [repair](https://developers.home-assistant.io/docs/core/platform/repairs)?) Alternatively, we can provide instructions for users to migrate themselves.

Additionally, to avoid confusion, we should revert the repository link to the previous one.

**Comment by catduckgnaf** [comment]
Hello @osk2 ,

Thank you for feedback, and the fact it was such a breaking change is why I had changed the repository, and to test myself as I was unsure of best way to handle it.

I have not used repair before, but that looks like an interesting solution.

I think given the fact this integration is yaml config, and likely not high usage base, it would be OK to list upgrade steps.

I can make the repo changes, and maybe after you merge make release 3.20? (that aligns with latest upstream that I synced changes with)

It should be essentially as simple as renaming the platform under media_player.yaml

Of course the old integration should be removed, but I vote for release notes.

Thoughts?

**Comment by osk2** [comment]
I agree with you that providing a release note would be sufficient.
However, I need to test everything before publishing with a release note.

**Comment by catduckgnaf** [comment]
> I agree with you that providing a release note would be sufficient. However, I need to test everything before publishing with a release note.

Of Course! I wouldn't expect anything else. After this part is done. Let me know if you would consider making me a contributor to the project on your repo. I do plan to continue work and more features. 

You can see because I made a release 0.2.2 that is what prompts the upgrade in HACS. I also think we should continue doing that going forward. It is a best practice for providing updates and it is very easy, even if you only have github draft the notes for you.
Also see for example https://github.com/catduckgnaf/ryobi_gdo

Good timing since upstream is on 3.2.0 anyway. :)  Let me know any changes, or I also allowed edits for the maintainer, if you want to go ahead and make any you see fit.

**Review by osk2 — APPROVED** [review]

**Comment by osk2** [comment]
v3.2.2 was released yesterday. 🎉 

Feel free to submit more PRs if you would like to contribute further!

**Comment by catduckgnaf** [comment]
Thanks! Will do.

**Pull request merged**
